### ISSUE TITLE
Add page - "Media"

### ISSUE THREAD

**Issue by hayleyw7** [nditcommunity/nditcommunity.github.io#10]
- Show media/press page when user clicks "media" in navbar.
- Hide everything else but the header and footer.

Include these links for now, and we'll add more as they come:
  - https://design-jobs.framer.website/neurodiversity-in-tech
  - https://www.youtube.com/watch?v=9jWzUhdn5C0
  - https://www.youtube.com/watch?v=EStNdU5JQo4
  - https://www.toledosua.org/alumnae/news/post/~board/alumnae-news/post/making-an-impact-hayley-witherell

**Comment by royemosby** [comment]
Stubbed media page in convert_to_ssg
