### ISSUE TITLE
Split JS into multiple files

### ISSUE THREAD

**Issue by hayleyw7** [nditcommunity/nditcommunity.github.io#30]
We should probably brainstorm a bit on how we do this. There are a lot of different ways.

**Comment by royemosby** [comment]
The simplest approach that I can think of right now is to place the theme and analytic scripts into all pages then only apply other scripts on a per-page basis. I've assembled the layouts and partials to use [liquid templates](https://liquidjs.com/index.html) so we can conditionally add scripts in any place based on some frontmatter property. I am thinking of probably a `script: ["script1-name", "script2-name"]` approach in the frontmatter of each page.
