### ISSUE TITLE
Implement page path routing

### ISSUE THREAD

**Issue by hayleyw7** [nditcommunity/nditcommunity.github.io#31]
Once the framework is structured for current content, we can easily set up future pages to work with it.

## Path ideas so far
- `/`
- `/resources`
- `/contact`
- `/media`  (_tentative_ name - maybe `/press`)
- `/about` (_tentative_ name - maybe `/vision` or `/mission`)
- `/code-of-conduct` (_tentative name_ - maybe `/code`, `/coc`, `/conduct`, `/rules`, etc)
- `/spaces` (_tentative name_ - maybe `/channels`, `/slack`, `/community`, etc)
- `/team` (_tentative name_ - leadership & "special thanks" to og site/logo contributors)
- `/contribute` (_tentative name_ - maybe how folks can contribute to site, content creation, etc)

**Comment by royemosby** [comment]
@hayleyw7 We're getting into SSG territory :-) Headers, footers, and navs can be componentized and that will save a lot on the look and feel for each page.

**Comment by hayleyw7** [comment]
@royemosby Feel free to edit this ticket you are envisioning, and I will stand behind it fully!
