### ISSUE TITLE
Bug - icon.svg 404

### ISSUE THREAD

**Issue by galactic-src** [nditcommunity/nditcommunity.github.io#66]
I've been nosing around to find an easy first issue and spotted in eleventy.config.js the icon.svg file passthrough path has a rogue space creeping in. Sure enough, locally I get a 404 for icon.svg.

I've fixed it on a local branch, but I don't have permissions to create a branch here. Ordinarily I would make a fork and make a PR from that. However, I saw you don't want people making forks in the contributor notes.

How shall I proceed?

Thanks!

**Comment by hayleyw7** [comment]
@galactic-src I shot you a message on slack. We will get it resolved.

**Comment by galactic-src** [comment]
My bad, turns out I hadn't set up GH SSH on a new laptop :see_no_evil:
Sorted, thanks!
