### ISSUE TITLE
Replace social icons with more consistent ones*

### ISSUE THREAD

**Issue by hayleyw7** [nditcommunity/nditcommunity.github.io#72]
This is a great one for a designer or anyone with design software experience.

https://github.com/nditcommunity/nditcommunity.github.io/pull/88

**Comment by galactic-src** [comment]
Which icons do you have in mind? And when you say "circle border radius", what exactly do you mean?

A screenshot might help to make it really clear! :pray:

**Comment by hayleyw7** [comment]
@galactic-src The built-in circle around the logos isn't the same width. Think of it like a border inside the actual png, with some being 1px and some being 3px. I'm working on this though! Best option is probably just using new icons.
