### ISSUE TITLE
Fix overlap & scroll in short windows

### ISSUE THREAD

**Issue by hayleyw7** [nditcommunity/nditcommunity.github.io#82]
https://github.com/nditcommunity/nditcommunity.github.io/pull/86
- 
- On certain window resolutions, a scrollbar appears when it's not needed.

![Scrollbar](https://github.com/user-attachments/assets/50180176-1ebe-496a-bb2a-7719c0898a4e)

- On certain shorter window resolutions, there is text overlap.

![Text overlap](https://github.com/user-attachments/assets/59145fa9-a2a8-499f-9dc7-09c2b2b2dcc5)

**Comment by hayleyw7** [comment]
@galactic-src This was my bad. I'm glad to fix it unless you want to. It's my fault! Just putting it in here so we don't forget.

**Comment by crunchydosa123** [comment]
hi, is someone assigned to this? i can help

**Comment by galactic-src** [comment]
I think it's `.home {flex; align-items: center}` causing overflow.

I thought of a couple of ways forward:
- keep it vertically centered and hide the overflow, and show a scrollbar
- keep the content at the top of the page with `{align-items: flex-start}` (I guess the page might look a bit empty for larger sizes)
- or the behaviour could change depending how tall the screen is using a media query (but then we need to remember to test at the breakpoint in future)

@crunchydosa123 your help would be much appreciated, go for it!
You might have some better possibilities to add 

@hayleyw7 any preference?
