### ISSUE TITLE
Sun icon misaligned on mobile

### ISSUE THREAD

**Issue by hayleyw7** [nditcommunity/nditcommunity.github.io#83]
On mobile, the sun icon is misaligned.

This does not happen when emulating mobile in Chrome, but it is happening on actual mobile devices.

![Misaligned icon](https://github.com/user-attachments/assets/324f5a82-baf5-4452-9f21-202534e9828b)

**Comment by galactic-src** [comment]
This may just be down to the available fonts - this is what I see on Linux (Ubuntu 22.04) if I put the two icons side by side.

![Screenshot from 2024-11-16 08-30-31](https://github.com/user-attachments/assets/7e8ddd44-be44-4d5c-8758-4ec84d205998)

**Comment by galactic-src** [comment]
Some possible fixes:
- choose some more widely-supported Unicode codepoints (I presume they would be rendered in the same font if they were both supported)
- add a package like [font-awesome](https://fontawesome.com/)
- supply a font which has appropriate support (e.g. something from Google Fonts) and override font-family in styles here

**Comment by galactic-src** [comment]
example using Google Fonts https://github.com/nditcommunity/nditcommunity.github.io/pull/84
